"""empty message

Revision ID: 3f947e124036
Revises: 
Create Date: 2019-08-20 14:46:19.976911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f947e124036'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatcontent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machingchat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('gp', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'delcomments', 'deletepost', ['post_id'], ['id'])
    op.create_foreign_key(None, 'deletepost', 'users', ['author_id'], ['id'])
    op.drop_constraint('follows_ibfk_1', 'follows', type_='foreignkey')
    op.drop_constraint('follows_ibfk_2', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'users', ['followed_id'], ['id'])
    op.drop_constraint('posts_ibfk_1', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.alter_column('users', 'profile_filename',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text("'information.png'"))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'profile_filename',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text("'information.png'"))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_ibfk_1', 'posts', 'users', ['author_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key('follows_ibfk_2', 'follows', 'users', ['followed_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('follows_ibfk_1', 'follows', 'users', ['follower_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'deletepost', type_='foreignkey')
    op.drop_constraint(None, 'delcomments', type_='foreignkey')
    op.drop_table('machingchat')
    op.drop_table('chatcontent')
    # ### end Alembic commands ###
